version: '2'
services:
  mongo:
    image: mongo:5.0.24 # latest version for MongoDB Atlas
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ../mock/mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: example
      TZ: Asia/Tokyo